{% set name = "asgi-lifespan" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asgi-lifespan-{{ version }}.tar.gz
  sha256: d46a31ff681e9edf1f776c9f61cf8fa6274cc66fca8cb4f11e940b1183e18842

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.7
  run:
    - async-exit-stack
    - python >=3.7
    - sniffio

test:
  imports:
    - asgi_lifespan
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/florimondmanca/asgi-lifespan
  summary: Programmatic startup/shutdown of ASGI apps.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - williamjamir
